# Default configuration for API Gateway
server:
  port: 8080

spring:
  cloud:
    gateway:
      # Default timeouts
      httpclient:
        connect-timeout: 5000
        response-timeout: 5000

      # Default filter configuration
      default-filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 10
            redis-rate-limiter.burstCapacity: 20
            key-resolver: "#{@ipKeyResolver}"
        - AddResponseHeader=X-Response-Time, ${now:iso}
        - AddResponseHeader=X-Api-Gateway, API-Gateway
        - RemoveRequestHeader=Cookie

      # Global CORS configuration
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            maxAge: 3600

  # Redis configuration for rate limiting
  redis:
    host: localhost
    port: 6379

  # Security configuration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000

# Resilience4j Circuit Breaker configuration
resilience4j:
  circuitbreaker:
    instances:
      toolRegistryCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
      flowRegistryCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
      executionEngineCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
      llmProcessingCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10

  timelimiter:
    instances:
      toolRegistryCircuitBreaker:
        timeoutDuration: 5s
      flowRegistryCircuitBreaker:
        timeoutDuration: 5s
      executionEngineCircuitBreaker:
        timeoutDuration: 10s
      llmProcessingCircuitBreaker:
        timeoutDuration: 30s

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway,circuitbreakers
  endpoint:
    health:
      show-details: when-authorized
      group:
        readiness:
          include: redis, circuitBreakers
  health:
    circuitbreakers:
      enabled: true
    redis:
      enabled: true
  metrics:
    tags:
      application: api-gateway

# Logging configuration
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.http.server.reactive: INFO
    org.springframework.web.reactive: INFO
    reactor.netty: INFO
    binhnvh.apigateway: DEBUG