# Development environment configuration for API Gateway
server:
  port: 8080

spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 10000
        response-timeout: 10000

      # Higher rate limits for development
      default-filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 50
            redis-rate-limiter.burstCapacity: 100
            key-resolver: "#{@ipKeyResolver}"
        - AddResponseHeader=X-Response-Time, ${now:iso}
        - AddResponseHeader=X-Api-Gateway, API-Gateway-Dev
        - RemoveRequestHeader=Cookie

      # Routes defined here will override the Java configuration
      routes:
        # User Management Service Routes
        - id: user-management-service
          uri: lb://user-management
          predicates:
            - Path=/api/auth/**,/api/users/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$1
            - AddRequestHeader=X-Gateway-Source, api-gateway
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 50
                redis-rate-limiter.burstCapacity: 100
                key-resolver: "#{@ipKeyResolver}"
            - name: CircuitBreaker
              args:
                name: userManagementCircuitBreaker
                fallbackUri: forward:/fallback/user-management

        # Tool Registry Service Routes
        - id: tool-registry-service
          uri: lb://tool-registry-service
          predicates:
            - Path=/api/tools/**
          filters:
            - RewritePath=/api/tools/(?<segment>.*), /tool-registry/$1
            - AddRequestHeader=X-Gateway-Source, api-gateway
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 50
                redis-rate-limiter.burstCapacity: 100
                key-resolver: "#{@ipKeyResolver}"
            - name: CircuitBreaker
              args:
                name: toolRegistryCircuitBreaker
                fallbackUri: forward:/fallback/tool-registry

        # Flow Registry Service Routes
        - id: flow-registry-service
          uri: lb://flow-registry-service
          predicates:
            - Path=/api/flows/**
          filters:
            - RewritePath=/api/flows/(?<segment>.*), /flow-registry/$1
            - AddRequestHeader=X-Gateway-Source, api-gateway
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 50
                redis-rate-limiter.burstCapacity: 100
                key-resolver: "#{@ipKeyResolver}"
            - name: CircuitBreaker
              args:
                name: flowRegistryCircuitBreaker
                fallbackUri: forward:/fallback/flow-registry

        # Execution Engine Service Routes
        - id: execution-engine-service
          uri: lb://execution-engine-service
          predicates:
            - Path=/api/executions/**
          filters:
            - RewritePath=/api/executions/(?<segment>.*), /execution-engine/$1
            - AddRequestHeader=X-Gateway-Source, api-gateway
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 50
                redis-rate-limiter.burstCapacity: 100
                key-resolver: "#{@ipKeyResolver}"
            - name: CircuitBreaker
              args:
                name: executionEngineCircuitBreaker
                fallbackUri: forward:/fallback/execution-engine

        # LLM Processing Service Routes
        - id: llm-processing-service
          uri: lb://llm-processing-service
          predicates:
            - Path=/api/llm/**
          filters:
            - RewritePath=/api/llm/(?<segment>.*), /llm-processor/$1
            - AddRequestHeader=X-Gateway-Source, api-gateway
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 20
                redis-rate-limiter.burstCapacity: 50
                key-resolver: "#{@ipKeyResolver}"
            - name: CircuitBreaker
              args:
                name: llmProcessingCircuitBreaker
                fallbackUri: forward:/fallback/llm-processor

# Add circuit breaker configuration for User Management Service
resilience4j:
  circuitbreaker:
    instances:
      userManagementCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
      toolRegistryCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
      # Other circuit breakers remain unchanged...

  timelimiter:
    instances:
      userManagementCircuitBreaker:
        timeoutDuration: 5s
      toolRegistryCircuitBreaker:
        timeoutDuration: 5s
      # Other time limiters remain unchanged...

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://eureka:eureka@localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 10