# Development environment configuration for API Gateway
server:
  port: 8080

spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 10000
        response-timeout: 10000

      # Higher rate limits for development
      default-filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 50
            redis-rate-limiter.burstCapacity: 100
            key-resolver: "#{@ipKeyResolver}"
        - AddResponseHeader=X-Response-Time, ${now:iso}
        - AddResponseHeader=X-Api-Gateway, API-Gateway-Dev
        - RemoveRequestHeader=Cookie

      # Routes defined here will override the Java configuration
      routes:
        - id: tool-registry-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/tools/**
          filters:
            - RewritePath=/api/tools/(?<segment>.*), /tool-registry/$1
            - AddRequestHeader=X-Gateway-Source, api-gateway
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 50
                redis-rate-limiter.burstCapacity: 100
                key-resolver: "#{@ipKeyResolver}"
            - name: CircuitBreaker
              args:
                name: toolRegistryCircuitBreaker
                fallbackUri: forward:/fallback/tool-registry

        - id: flow-registry-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/flows/**
          filters:
            - RewritePath=/api/flows/(?<segment>.*), /flow-registry/$1
            - AddRequestHeader=X-Gateway-Source, api-gateway
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 50
                redis-rate-limiter.burstCapacity: 100
                key-resolver: "#{@ipKeyResolver}"
            - name: CircuitBreaker
              args:
                name: flowRegistryCircuitBreaker
                fallbackUri: forward:/fallback/flow-registry

        - id: execution-engine-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/executions/**
          filters:
            - RewritePath=/api/executions/(?<segment>.*), /execution-engine/$1
            - AddRequestHeader=X-Gateway-Source, api-gateway
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 50
                redis-rate-limiter.burstCapacity: 100
                key-resolver: "#{@ipKeyResolver}"
            - name: CircuitBreaker
              args:
                name: executionEngineCircuitBreaker
                fallbackUri: forward:/fallback/execution-engine

        - id: llm-processing-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/llm/**
          filters:
            - RewritePath=/api/llm/(?<segment>.*), /llm-processor/$1
            - AddRequestHeader=X-Gateway-Source, api-gateway
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 20
                redis-rate-limiter.burstCapacity: 50
                key-resolver: "#{@ipKeyResolver}"
            - name: CircuitBreaker
              args:
                name: llmProcessingCircuitBreaker
                fallbackUri: forward:/fallback/llm-processor

  # Redis configuration - using simple rate limiter for dev
  redis:
    host: localhost
    port: 6379

  # Security configuration - simplified for development
  security:
    user:
      name: admin
      password: admin

# Resilience4j - more permissive settings for development
resilience4j:
  circuitbreaker:
    instances:
      toolRegistryCircuitBreaker:
        slidingWindowSize: 10
        minimumNumberOfCalls: 3
        permittedNumberOfCallsInHalfOpenState: 5
        waitDurationInOpenState: 5s
        failureRateThreshold: 70
      flowRegistryCircuitBreaker:
        slidingWindowSize: 10
        minimumNumberOfCalls: 3
        permittedNumberOfCallsInHalfOpenState: 5
        waitDurationInOpenState: 5s
        failureRateThreshold: 70
      executionEngineCircuitBreaker:
        slidingWindowSize: 10
        minimumNumberOfCalls: 3
        permittedNumberOfCallsInHalfOpenState: 5
        waitDurationInOpenState: 5s
        failureRateThreshold: 70
      llmProcessingCircuitBreaker:
        slidingWindowSize: 10
        minimumNumberOfCalls: 3
        permittedNumberOfCallsInHalfOpenState: 5
        waitDurationInOpenState: 5s
        failureRateThreshold: 70

  timelimiter:
    instances:
      toolRegistryCircuitBreaker:
        timeoutDuration: 10s
      flowRegistryCircuitBreaker:
        timeoutDuration: 10s
      executionEngineCircuitBreaker:
        timeoutDuration: 20s
      llmProcessingCircuitBreaker:
        timeoutDuration: 60s

# Enhanced logging for development
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty: DEBUG
    binhnvh.apigateway: DEBUG

# Actuator - expose all endpoints in development
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always