# Development environment specific common configuration
spring:
  # Database configuration - default for development
  datasource:
    url: jdbc:h2:mem:dev-db
    username: sa
    password: password
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # H2 Console
  h2:
    console:
      enabled: true
      path: /h2-console
  application:
    resilience:
          circuit-breaker:
            force-open: false
          retry:
            enabled: true
            max-attempts: 3

# Enhanced logging for development
logging:
  level:
    binhnvh: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

# Actuator for development
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

# Resilience settings for development

# Enable API docs for development
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true