# Development environment specific configuration for User Management Service
server:
  port: 8081

spring:
  # Database configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/user_management_dev
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  # JPA/Hibernate configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Flyway migration configuration
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

# Logging
logging:
  level:
    binhnvh.usermanagement: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Eureka Client Configuration
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:eureka@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 10 # for development

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,flyway
  endpoint:
    health:
      show-details: always

# Application specific settings
application:
  security:
    jwt:
      secret-key: s5v8y/B?E(H+MbQeThWmZq4t7w!z%C&F)J@NcRfUjXn2r5u8x/A?D*G-KaPdSgVk
      expiration: 86400000  # 24 hours in milliseconds
      issuer: llm-workflow-system